-- Generated from the root agent directory CSV by find-a-home.
-- Applies an upsert by owned_website_url; it does not delete rows missing from the CSV.
insert into public.agent_directory (agent_name, owned_website_url, status, evidence_or_note)
values
  ('Akelius Residential', 'https://www.akelius.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Austin Homes', 'https://austinhomes.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Chancellors', 'https://www.chancellors.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Chestertons', 'https://www.chestertons.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Choice Homes', 'https://www.choicehomes.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('David Astburys', 'https://www.davidastburys.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Dexters', 'https://www.dexters.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Dimension Estates', 'https://www.dimension-estates.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Elkay Properties', 'https://www.elkayproperties.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Ellis & Co', 'https://www.ellisandco.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Ernest-Brooks International', 'https://www.ernest-brooks.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Essential Living', 'https://www.essentialliving.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Foxtons', 'https://www.foxtons.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Grainger', 'https://www.graingerplc.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Hamptons', 'https://www.hamptons.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Hello Neighbour', 'https://www.hello-neighbour.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Home Made', 'https://www.home-made.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Homefinders', 'https://www.homefinders.net', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Hotblack Desiato', 'https://www.hotblackdesiato.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('IDM Estates', 'https://www.idmestates.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Inner City Estates', 'https://www.innercityestates.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('KFH', 'https://www.kfh.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Knight Frank', 'https://www.knightfrank.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Letio', 'https://www.letio.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Maxwells Estates', 'https://maxwellsestates.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Next Move', 'https://www.nextmove.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('OpenRent', 'https://www.openrent.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Portico', 'https://www.portico.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('RE/MAX Star', 'https://www.remaxstar.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('RentCityFlat', 'https://www.rentcityflat.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Rosewood Estates', 'https://www.rosewoodestates.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Sandra Davidson Estate Agents', 'https://www.sandradavidson.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Savills', 'https://www.savills.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Scraye', 'https://www.scraye.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Stirling Ackroyd', 'https://www.stirlingackroyd.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Victor Michael', 'https://www.victormichael.com', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Victorstone', 'https://www.victorstone.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Winkworth', 'https://www.winkworth.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Zen Homes', 'https://www.zenhomes.co.uk', 'confirmed_recent', 'From initial OnTheMarket recent-listings pass for E8/E9/E2/N1'),
  ('Alex Crown Lettings & Estate Agents', 'https://www.alexcrown.co.uk', 'confirmed_recent', 'OnTheMarket E8 listing showed added yesterday; owned site verified via Google'),
  ('Andrew Lloyd Estates', 'https://andrewlloyd.net', 'confirmed_recent', 'OnTheMarket N1 page 2 showed added <7 days; owned site verified via Google'),
  ('Knight Bishop', 'https://www.knightbishop.co.uk', 'confirmed_recent', 'OnTheMarket E9 listing showed added yesterday; owned site verified via Google'),
  ('Felicity J. Lord', 'https://www.fjlord.co.uk', 'confirmed_recent', 'OnTheMarket E9 listing showed added <7 days; owned site verified via Google'),
  ('Harris Brown', 'https://www.harrisbrown.co.uk', 'confirmed_recent', 'OnTheMarket N1 listing showed added today; owned site verified via Google'),
  ('Neilson & Bauer', 'https://www.neilsonbauer.com', 'confirmed_recent', 'OnTheMarket N1 listing showed added today; owned site verified via Google'),
  ('Let UK Home / Letukhome', 'https://www.letukhome.co.uk', 'confirmed_recent', 'OnTheMarket N1 listing showed reduced today; owned site verified via Google'),
  ('Hunters', 'https://www.hunters.com', 'confirmed_recent', 'OnTheMarket N1 listing showed Hunters Shoreditch added yesterday; owned site verified via Google'),
  ('Keatons', 'https://www.keatons.com', 'candidate_unverified_30_days', 'Found on OnTheMarket listing marked added >14 days; may be within 30 days but not publicly confirmed'),
  ('John D Wood & Co', 'https://www.johndwood.co.uk', 'candidate_unverified_30_days', 'Found on OnTheMarket listing marked added >14 days; may be within 30 days but not publicly confirmed'),
  ('Filey Properties', 'https://www.fileyproperties.com', 'candidate_unverified_30_days', 'Found on OnTheMarket listing marked added >14 days; may be within 30 days but not publicly confirmed'),
  ('Bigmove Sales & Lettings', 'https://www.bigmove.uk.com', 'candidate_unverified_30_days', 'Found on OnTheMarket listing marked added >14 days; may be within 30 days but not publicly confirmed'),
  ('Edward Lewis & Co', 'https://www.edwardlewis.com', 'candidate_unverified_30_days', 'Found on OnTheMarket listing marked added >14 days; URL not fully verified in previous pass'),
  ('Druce', 'https://www.druce.com', 'candidate_unverified_30_days', 'Found on OnTheMarket listing marked added >14 days; may be within 30 days but not publicly confirmed')
on conflict (owned_website_url) do update set
  agent_name = excluded.agent_name,
  status = excluded.status,
  evidence_or_note = excluded.evidence_or_note,
  updated_at = now();
